resolver:    lts-13.12

packages:
- .

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  dcce28e31c8e30b65096ef24178c65f749b24e5c

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8093bee3480265952b6fb1694bef3498d5182859

- bioinformatics-toolkit-0.5.1
- clustering-0.4.0
- HsHTSLib-1.3.2.3
