resolver:    lts-11.3

packages:
- .

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  a8cd7f979766c4f2eefed45bde6ac695aec6b80c

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8093bee3480265952b6fb1694bef3498d5182859

- bioinformatics-toolkit-0.5.0
- clustering-0.4.0
- HsHTSLib-1.3.2.3
